### PR TITLE
Unity Mole Fraction & MFR Issue

### PR DESCRIPTION
**Pull request by t-sahin**
This pull request is directed toward Issue #1 Revert Unity to Properly Use Mole Fractions Again.

Four new variables, "_FlowRates#", to the UI/Reactor.cs file were added and changed the mole fractions, not molar flow rates, to be used for the calculation of the wedges. Though the molar flow rate values is what remained as displayed. (See commit 0cba386).

Within the CommClient.cs file, the values for "_FlowRates#" were set equal to kinetics.Kinetics.MolarFlowRate. Additionally, a check for the mole fraction sum, 'sum <= 1.0' was inserted into a for loop to ensure that it's a valid value. (See commit d7679ea).

### CODE REVIEW

**Comment by t-sahin** [comment]
With this last commit fixing a semicolon (see commit cc32af7), the code is exactly how Heta and I tested it. It appeared successful with MFR being displayed, and the wedges also appeared to be in proportion to the actual MFR values.

**Comment by whitead** [comment]
@RainierBarrett and @t-sahin, what are your thoughts on encapsulating the shader variable modification into the `Reactor.cs` so that the `CommClient.cs` doesn't need to know so much about the `Reactor.cs` class. For example, we could add `set_molefrac` and/or `set_flowrate` methods to the `Reactor.cs` class. Thoughts?

**Comment by t-sahin** [comment]
I see no reason why that couldn't work. It might very well be more efficient, too.

Tomorrow I can test a new commit that encapsulates the shader variable modification within the Reactor.cs file to see how it works.

**Comment by t-sahin** [comment]
Neither Maghesree or I have key access to the room with the AR Table so I will test this commit (2a8ed70) on Monday, not today.

**Comment by t-sahin** [comment]
@whitead and @RainierBarrett , the code based on commit 98c994f does not have a build error, however when tested, only a gray ring encircles the reactors and no molar flow rates are displayed either. After another few hours of testing and adjusting several pieces of code, I could not identify a particular issue that would cause this.

Two questions I came across from CommClient.cs file in commit c908949: (1) Why are we using type MeshRenderer for rend in line 482? When I tested <Renderer> with the original code (i.e. when there were no setMethods) everything seemed to work just as well as without it. (2) What is the purpose of line 483?  rend.material.shader is never called anywhere within the CommClient.cs file, and when commented out the code also seemed to work just as well.

**Comment by t-sahin** [comment]
@whitead and @RainierBarrett , I thought through this last night: The setMethods were creating an entirely new renderer within the method. So ultimately I made a new input within the setMethods to pass the currently-used renderer within the CommClient.cs into the method. It worked (commit 6e2e011) when tested this morning.

Also, line 483 (see above comment) was deleted after confirming with Rainier that it has no functional use.

**Review by RainierBarrett — COMMENTED** [review]
Encapsulated code works great!
Just had one tweak needed to find existing Reactor objects instead of creating them at each update.

**Pull request merged**
